modLoader="lowcodefml"
loaderVersion="[59,)"
license="MIT"

[[mods]]
modId="silly_eatables"
version="4.0.0-pre"
displayName="Silly Eatables"
logoFile="pack.png"
displayURL="https://modrinth.com/datapack/silly_eatables"
credits="https://github.com/Classics-Craftworks/Silly_Eatables/wiki/Credits"
authors="Classic36"
description="Eat things you shouldn't with these silly food recipes!"

[[dependencies.silly_eatables]]
    modId="forge"
    mandatory=true
    versionRange="[59,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.silly_eatables]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.9]"
    ordering="AFTER"
    side="BOTH"